config/routes.rb
Rails.application.routes.draw do

  root :to => 'staticpages#home'

  

  get 'staticpages/private'

  get    '/login',   to: 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/logout' => 'sessions#destroy'
  resources :sessions

  resources :users, only:[:new, :create, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :warning, :danger, :info
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


	def new
	end

	def create
	user = User.find_by(email: params[:session][:email].downcase)
	if user && user.authenticate(params[:session][:password])
	  log_in user
	  redirect_to root_url
	else
	  flash.now[:danger] = 'Invalid email/password combination'
	  render 'new'
	end
	end

	def destroy
	  session[:user_id] = nil      
	  redirect_to root_url
	end

	def log_in(user)
	  session[:user_id] = user.id
	end

	def current_user
	  if session[:user_id]
	    User.find_by(id: session[:user_id])
	  end
	end

end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def home
  end

  def private
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id 
      flash[:success] = "Welcome to Private Club"
      redirect_to root_url
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  private

  def user_params
  params.require(:user).permit(:name, :last_name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    case flash_type
      when :success
        "alert-success"
      when :error
        "alert-error"
      when :alert
        "alert-block"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

 
  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_messages.html.erb
<div class="container">
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>
</div>

app/views/layouts/_header.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light"> 
    <div class="container">
    <a class="navbar-brand" href="/">🌷</a> 
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="nav navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="/">Home</a>
        </li>

        <% if logged_in? %>
        
        <li class="nav-item">
          <%= link_to "Members", staticpages_private_path,
          :class => "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", logout_path, method: :delete, 
          :class => "nav-link" %>
        </li>
        <% else %>
        <li class="nav-item">
          <a class="nav-link" href="/login">Sign in</a>
        </li>

        <li class="nav-item">
          <%= link_to "Sign up", new_user_path,
          :class => "nav-link" %>
        </li>
        <% end %>

      </ul>
    </div>
    </div>
  </nav>
</header>

app/views/layouts/_rails_default.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title><%= (yield(:title)) %></title>
  <%= render 'layouts/rails_default' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <%= render partial: "layouts/flash_messages", flash: flash %> 

  <%= yield %>

  
  </body>
</html>

app/views/staticpages/home.html.erb
<% provide(:title, 'Home') %>

<div class="jumbotron jumbotron-fluid">
	<div class="container">
		<h1>Welcome !</h1>
		<h5 class="mt-3">Private Club </h5>
		<% if logged_in? %>
		<%= link_to "Members list", 'staticpages/private', class: "btn btn-dark mt-4" %>
		<% else %>
        <a class="btn btn-primary mt-4" href="/login">Sign in</a>
		<% end %>
	</div>
</div>

app/views/staticpages/private.html.erb
<% provide(:title, 'Members') %>

<div class="container mt-5 mb-5">
<% if logged_in? %>
<h3 class="mb-5">Members :</h3>

<table class="table mt-5">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Last name</th>
      <th>Email</th>
    </tr>
  </thead>
<tbody>
<% User.all.each do |user| %>
    <tr>
      <th><%= user.id %></th>
      <td><%= user.name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.email %></td>
    </tr>
<% end %>

<% else %>
<h3> Please sign in to see the members </h3>
<a class="btn btn-primary mt-4" href="/login">Sign in</a>
<% end %>

</tbody>
</table>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="container mt-5 mb-5"> <!-- New user form -->
	<div class="form-group col-md-6">
		<h5 class="mb-5">Let's create your account!</h5>
				
		<%= form_for @user do |f|%>


		    <div class="form-group">
		      <label>Name</label>  
		      <%= f.text_field :name, class: "form-control", placeholder: "John" %>
		    </div>

		    <div class="form-group">
		      <label>Family name</label>  
		      <%= f.text_field :last_name, class: "form-control", placeholder: "Doe" %>
		    </div>

		    <div class="form-group">
		      <label>Email</label>  
		      <%= f.email_field :email, class: "form-control", placeholder: "johndoe@email.com" %>
		    </div>

		    <div class="form-group">
		      <label>Password</label>  
		      <%= f.password_field :password, class: "form-control", placeholder: "*******" %>
		    </div>

		    <div class="form-group">
		      <label>Password confirmation</label>  
		      <%= f.password_field :password_confirmation, class: "form-control", placeholder: "*******" %>
		    </div>
		    
		    <div class="form-group">
		      <button type="submit" class="btn btn-primary">Register</button>
		    </div>
	  </div>
	<%end%>
</div>

app/views/users/show.html.erb
<div class="container mt-5">
	<h1>Salut petit user</h1>
</div>